"""Seed task set for the vim benchmark.

Each task: the model receives (instruction, start buffer) and must output a
keystroke sequence in the harness notation. The reference is a known-good,
near-optimal solution used for the efficiency metric and for verifying the
task is solvable by construction (see verify.py).
"""

TASKS = [
    # ---------------- Tier 1: mechanical editing ----------------
    dict(id="t1-delete-second-line", tier=1, title="Delete the second line",
         instruction="Delete the second line of the file.",
         start="alpha\nbeta\ngamma\ndelta\n",
         target="alpha\ngamma\ndelta\n",
         reference="jdd:wq<CR>"),
    dict(id="t1-delete-lines-2-3", tier=1, title="Delete lines 2 through 3",
         instruction="Delete lines 2 and 3 of the file.",
         start="a\nb\nc\nd\n",
         target="a\nd\n",
         reference="j2dd:wq<CR>"),
    dict(id="t1-swap-first-two", tier=1, title="Swap the first two lines",
         instruction="Swap the first two lines of the file.",
         start="a\nb\nc\n",
         target="b\na\nc\n",
         reference="ddp:wq<CR>"),
    dict(id="t1-copy-first-to-end", tier=1, title="Copy the first line to the end",
         instruction="Copy the first line and paste the copy after the last line.",
         start="a\nb\n",
         target="a\nb\na\n",
         reference="yyGp:wq<CR>"),
    dict(id="t1-join-three", tier=1, title="Join three lines into one",
         instruction="Join all three lines into a single line, separated by single spaces.",
         start="a\nb\nc\n",
         target="a b c\n",
         reference="3J:wq<CR>"),
    dict(id="t1-uppercase-line-2", tier=1, title="Uppercase the second line",
         instruction="Convert the entire second line to uppercase.",
         start="abc\ndef\n",
         target="abc\nDEF\n",
         reference="jgUU:wq<CR>"),
    dict(id="t1-indent-2sp", tier=1, title="Indent lines 2-3 by two spaces",
         instruction="Indent lines 2 and 3 by exactly two spaces each.",
         start="a\nb\nc\nd\n",
         target="a\n  b\n  c\nd\n",
         reference=":set sw=2<CR>j2>>:wq<CR>"),
    dict(id="t1-change-word-line-5", tier=1, title="Change the word on line 5",
         instruction="On line 5, replace the word with FIVE (uppercase).",
         start="one\ntwo\nthree\nfour\nfive\nsix\n",
         target="one\ntwo\nthree\nfour\nFIVE\nsix\n",
         reference="5GcwFIVE<Esc>:wq<CR>"),
    dict(id="t1-delete-last-line", tier=1, title="Delete the last line",
         instruction="Delete the last line of the file.",
         start="a\nb\nc\n",
         target="a\nb\n",
         reference="Gdd:wq<CR>"),
    dict(id="t1-reverse-lines", tier=1, title="Reverse the order of all lines",
         instruction="Reverse the order of all lines in the file.",
         start="a\nb\nc\n",
         target="c\nb\na\n",
         reference=":g/^/m0<CR>:wq<CR>"),

    # ---------------- Tier 2: motions, text objects, macros ----------------
    dict(id="t2-change-inside-quotes", tier=2, title="Change text inside quotes",
         instruction='Replace the text inside the double quotes with goodbye.',
         start='say "hello world" loudly\n',
         target='say "goodbye" loudly\n',
         reference='f"ci"goodbye<Esc>:wq<CR>'),
    dict(id="t2-delete-inside-parens", tier=2, title="Delete text inside parentheses",
         instruction="Delete everything inside the parentheses (keep the parentheses).",
         start="sum(1, 2, 3)\n",
         target="sum()\n",
         reference="f(di(:wq<CR>"),
    dict(id="t2-semicolons-macro", tier=2, title="Append semicolons with a macro",
         instruction="Append a semicolon to the end of every line. Using a macro is the idiomatic way.",
         start="a\nb\nc\n",
         target="a;\nb;\nc;\n",
         reference="qaA;<Esc>jq2@a:wq<CR>"),
    dict(id="t2-quote-first-word", tier=2, title="Wrap the first word in quotes",
         instruction='Wrap only the first word in double quotes.',
         start="hello world\n",
         target='"hello" world\n',
         reference='bi"<Esc>ea"<Esc>:wq<CR>'),
    dict(id="t2-delete-csv-field", tier=2, title="Delete the second CSV field",
         instruction="Delete the second comma-separated field (including its leading comma and space).",
         start="foo, bar, baz\n",
         target="foo, baz\n",
         reference="f,dt,:wq<CR>"),
    dict(id="t2-comment-visual-block", tier=2, title="Comment lines with visual block",
         instruction="Prefix each line with '# ' (hash + space) using visual block mode.",
         start="a\nb\nc\n",
         target="# a\n# b\n# c\n",
         reference="<C-V>jjI# <Esc>:wq<CR>"),
    dict(id="t2-change-first-foo", tier=2, title="Change only the first occurrence",
         instruction="Change only the FIRST occurrence of 'foo' to 'bar'. Leave the second one alone.",
         start="x\nfoo one\nfoo two\n",
         target="x\nbar one\nfoo two\n",
         reference="/foo<CR>cwbar<Esc>:wq<CR>"),
    dict(id="t2-swap-chars", tier=2, title="Swap the two characters",
         instruction="Swap the two characters on the line.",
         start="ab\n",
         target="ba\n",
         reference="xp:wq<CR>"),
    dict(id="t2-delete-to-eol", tier=2, title="Delete to end of line",
         instruction="Move to the first space, then delete from there to the end of the line.",
         start="hello world\n",
         target="hello\n",
         reference="f<Space>d$:wq<CR>"),
    dict(id="t2-duplicate-word", tier=2, title="Duplicate the first word",
         instruction="Duplicate the first word in place, so it appears twice separated by a space.",
         start="foo bar\n",
         target="foo foo bar\n",
         reference="ywP:wq<CR>"),

    # ---------------- Tier 3: ex commands ----------------
    dict(id="t3-substitute-all", tier=3, title="Substitute all occurrences",
         instruction="Replace every occurrence of 'foo' with 'bar' in the whole file.",
         start="foo 1\nfoo 2\n",
         target="bar 1\nbar 2\n",
         reference=":%s/foo/bar/g<CR>:wq<CR>"),
    dict(id="t3-delete-matching-lines", tier=3, title="Delete lines containing 'err'",
         instruction="Delete every line that contains the word 'err'.",
         start="err x\nok y\nerr z\n",
         target="ok y\n",
         reference=":%s/.*err.*//<CR>:g/^$/d<CR>:wq<CR>"),
    dict(id="t3-copy-matching-to-end", tier=3, title="Copy matching lines to the end",
         instruction="Copy every line containing 'err' to the end of the file (originals stay).",
         start="err x\nok y\nerr z\n",
         target="err x\nok y\nerr z\nerr x\nerr z\n",
         reference=":g/err/t$<CR>:wq<CR>"),
    dict(id="t3-sort-unique", tier=3, title="Sort lines, removing duplicates",
         instruction="Sort all lines alphabetically and remove duplicate lines.",
         start="b\na\nb\nc\n",
         target="a\nb\nc\n",
         reference=":sort u<CR>:wq<CR>"),
    dict(id="t3-uppercase-todo", tier=3, title="Uppercase lines starting with 'todo'",
         instruction="Uppercase every line that starts with 'todo'. Other lines stay unchanged.",
         start="todo fix\nship it\ntodo test\n",
         target="TODO FIX\nship it\nTODO TEST\n",
         reference=r":g/todo/s/.*/\U&/<CR>:wq<CR>"),
    dict(id="t3-move-range-top", tier=3, title="Move lines 2-3 to the top",
         instruction="Move lines 2 and 3 to the top of the file, preserving their order.",
         start="a\nb\nc\nd\n",
         target="b\nc\na\nd\n",
         reference=":2,3m0<CR>:wq<CR>"),

    # ---------------- Tier 4: composed transforms ----------------
    dict(id="t4-swap-csv-columns", tier=4, title="Swap the two CSV columns",
         instruction="On every line, swap the two comma-separated columns.",
         start="a,b\nc,d\n",
         target="b,a\nd,c\n",
         reference=r":%s/\([^,]*\),\(.*\)/\2,\1/<CR>:wq<CR>"),
    dict(id="t4-strip-trailing-ws", tier=4, title="Strip trailing whitespace",
         instruction="Remove all trailing whitespace (spaces and tabs) from every line.",
         start="a  \nb\t\nc\n",
         target="a\nb\nc\n",
         reference=r":%s/\s\+$//<CR>:wq<CR>"),
    dict(id="t4-extract-emails", tier=4, title="Extract email addresses",
         instruction="Replace each 'Name <email>' line with just the email address.",
         start="Alice <alice@x.com>\nBob <bob@y.org>\n",
         target="alice@x.com\nbob@y.org\n",
         reference=r":%s/.*<<\(.*\)>/\1/<CR>:wq<CR>"),
    dict(id="t4-dedent-and-strip", tier=4, title="Dedent and strip in one pass",
         instruction="Remove the two-space indent from the start of each line AND remove any trailing whitespace.",
         start="  a  \n  b\nc\n",
         target="a\nb\nc\n",
         reference=r":%s/^  //<CR>:%s/\s\+$//<CR>:wq<CR>"),
]
